version: "3.8"
services:
  proxy:
    image: studiconnect-proxy:latest
    container_name: studiconnect-proxy
    mem_limit: 1gb
    mem_reservation: 200m
    cpu_count: 1
    cpu_percent: 50
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 1m
      timeout: 10s
    depends_on:
      - frontend
      - backend
    volumes:
      - ~/studiconnect-appdata/log/proxy:/var/log/nginx
    ports:
      - "127.0.0.1:80:80"
    networks:
      main:
        ipv4_address: 192.168.10.2
        ipv6_address: fc00:1::2

  frontend:
    image: studiconnect-frontend:latest
    container_name: studiconnect-frontend
    mem_limit: 100m
    mem_reservation: 50m
    cpu_count: 1
    cpu_percent: 50
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 1m
      timeout: 10s
    depends_on:
      - backend
    networks:
      main:
        ipv4_address: 192.168.10.3
        ipv6_address: fc00:1::3

  backend:
    image: studiconnect-backend:latest
    container_name: studiconnect-backend
    depends_on:
      - db
      - redis
    # env_file:
    #  - .env.prod
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 1m
      timeout: 10s
    mem_limit: 200m
    mem_reservation: 50m
    cpu_count: 1
    cpu_percent: 50
    restart: on-failure
    user: "node:node"
    volumes:
      - ./data:/data:777
    networks:
      main:
        ipv4_address: 192.168.10.4
        ipv6_address: fc00:1::4

  mongo:
    image: studiconnect-db:latest
    container_name: studiconnect-db
    ports:
      - "127.0.0.1:27017:27017"
    healthcheck:
      test: 'bash -c "if mongo --eval ''quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)''; then exit 0; fi; exit 1;"'
      interval: 1m
      timeout: 10s
    mem_limit: 200m
    mem_reservation: 50m
    cpu_count: 1
    cpu_percent: 50
    volumes:
      - ~/studiconnect-appdata/mongo:/data/db
    networks:
      main:
        ipv4_address: 192.168.10.5
        ipv6_address: fc00:1::7
    restart: on-failure

  redis:
    image: studiconnect-redis:latest
    container_name: studiconnect-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ~/studiconnect-appdata/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1m
      timeout: 10s
    mem_limit: 200m
    mem_reservation: 50m
    cpu_count: 1
    cpu_percent: 50
    networks:
      main:
        ipv4_address: 192.168.10.6
        ipv6_address: fc00:1::6

networks:
  main:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/29
        - subnet: fc00:1::0/120
